INSERT INTO habilidades(nombre, efecto) VALUES ('Absorbe agua', 'Convierte agua en PS.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Absorbe electricidad', 'Convierte electricidad en PS.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Absorbe fuego', 'Aumenta la fuerza de los movimientos tipo fuego si el Pokémon recibe uno en vez de daño.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Aclimatación', 'Anula los efectos del clima.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Agallas', 'Sube el ataque si el Pokémon sufre un cambio de estado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Armadura batalla', 'Bloquea golpes críticos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ausente', 'Interviene cada dos rondas.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Bucle aire', 'Anula los efectos del clima.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cabeza roca', 'Evita el daño colateral causado por movimientos del usuario.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cacofonía', 'Evita ataques de sonido.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cambio color', 'Toma el tipo del movimiento rival.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Caparazón', 'Bloquea golpes críticos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Chorro arena', 'Crea una tormenta de arena.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Clorofila', 'Con sol, sube la velocidad.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Corte fuerte', 'Evita que baje el ataque.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cuerpo llama', 'Quema al mínimo contacto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cuerpo puro', 'Evita que bajen las estadísticas.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cura lluvia', 'Sube PS cuando llueve.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cura natural', 'Se cura al salir a la batalla.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Despiste', 'Evita la atracción.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Dicha', 'Promueve efectos secundarios.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Efecto espora', 'Duerme, paraliza o envenena al contacto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Electricidad estática', 'Paraliza al mínimo contacto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Energía pura', 'Sube el ataque.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Enjambre', 'Incrementa el poder de ataques tipo bicho.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Entusiasmo', 'Cambia precisión por Ataque.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Escama especial', 'Sube la defensa si sufre.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Escudo magma', 'Evita el congelamiento.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Espesura', 'Sube ataques tipo planta.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Espíritu vital', 'Evita el quedarse dormido.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Flexibilidad', 'Evita la parálisis.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Foco interno', 'Evita el retroceso.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Fuga', 'Facilita la huida.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Gran encanto', 'enamora al mínimo contacto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Hedor', 'Aleja a Pokémon salvajes.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Humedad', 'Evita la autodestrucción.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Humo blanco', 'Evita que bajen las estadísticas.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Iluminación', 'Facilita el encuentro con Pokémon salvajes.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Impulso', 'Aumenta la velocidad en cada turno.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Imán', 'Atrapa Pokémon de acero.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Inmunidad', 'Evita el envenenamiento.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Insomnio', 'Evita el quedarse dormido.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Insonorizar', 'Evita ataques de sonido.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Intimidación', 'Baja el ataque del rival.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Levitación', 'No sufre ataques tipo tierra.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Llovizna', 'Cambia el clima a lluvioso.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Lodo líquido', 'Al robar PS, hiere.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Madrugar', 'Despierta rápido al Pokémon.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Mar llamas', 'Sube ataques tipo fuego.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Más', 'Mejora con la habilidad Menos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Menos', 'Mejora con la habilidad Más.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Mudar', 'Se cura mudando la piel.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Nado rápido', 'Con lluvia, sube la velocidad.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ojocompuesto', 'Aumenta la precisión de los ataques.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Pararrayos', 'Atrae ataques de tipo eléctrico.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Piel tosca', 'Hiere al tacto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Polvo escudo', 'Evita efectos secundarios.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Potencia', 'Aumenta el ataque.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Predicción', 'Cambia de forma con el clima.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Presión', 'Baja los PP del enemigo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Punto tóxico', 'Envenena al mínimo contacto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Rastro', 'Copia la habilidad especial.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Recogida', 'Puede tomar objetos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ritmo propio', 'Evita la confusión.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Robustez', 'Anula golpes fulminantes.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Sebo', 'Protege del frío y calor.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Sequía', 'Cambia el clima a soleado en batalla.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Sincronía', 'Transmite problemas de estado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Sombratrampa', 'Evita que el enemigo huya.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Superguarda', 'Solo afectan golpes super efectivos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Torrente', 'Sube ataques tipo agua.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Trampa arena', 'Evita la huida.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Velo agua', 'Evita las quemaduras.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Velo arena', 'Aumenta evasión con Tormenta Arena.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ventosas', 'Fija el cuerpo con firmeza.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Viscosidad', 'Evita el robo de objetos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Vista lince', 'Evita que baje la precisión.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Adaptable', 'Potencia los movimientos del mismo tipo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Afortunado', 'Aumenta la posibilidad de producir un ataque crítico.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Alerta', 'Determina el ataque más potente del Pokémon rival.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Anticipación', 'Siente los ataques peligrosos del rival.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Antídoto', 'Sube PS si el Pokémon está envenenado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Audaz', 'Aumenta el poder de los ataques que causan retroceso.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cacheo', 'El Pokémon puede ver el objeto equipado del rival.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Colector', 'Atrae ataques de tipo agua lanzados a un Pokémon.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cromolente', 'Potencia los movimientos "poco eficaces".');
INSERT INTO habilidades(nombre, efecto) VALUES ('Defensa hoja', 'Previene problemas de estado con día soleado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Descarga', 'Ajusta el poder acorde con la habilidad del rival.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Don floral', 'Aumenta el poder con día soleado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Electromotor', 'Aumenta la rapidez si es golpeado con un ataque tipo eléctrico.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Encadenado', 'Incrementa la frecuencia de golpes en los ataques de golpeo múltiple.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Experto', 'Aumenta el poder de los ataques débiles.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Filtro', 'Mitiga los movimientos super efectivos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Francotirador', 'Potencia los movimientos que se vuelven críticos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Gula', 'Aumenta la rapidez del uso de las bayas equipadas.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Gélido', 'Sube PS con Granizo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Hidratación', 'Cura los problemas de estado si está lloviendo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ignífugo', 'Reduce el poder de los ataques tipo fuego.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ignorante', 'Ignora cualquier cambio en la habilidad del enemigo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Impasible', 'Sube la velocidad cada vez que el Pokémon retrocede.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Indefenso', 'El ataque del Pokémon y el del rival acertarán.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Inicio lento', 'Reduce el ataque y la velocidad.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Intrépido', 'Permite golpear a los Pokémon de tipo fantasma.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Irascible', 'Potencia el ataque tras recibir un golpe crítico.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Liviano', 'Sube la velocidad al perder un objeto equipado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Mal sueño', 'Reduce los PS del enemigo cuando duerme.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Manto níveo', 'Más evasión con Granizo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Multitipo', 'Cambia con la tabla equipada.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Muro mágico', 'Al Pokémon solo le afectan ataques directos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Nevada', 'El Pokémon invoca una tormenta de granizo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Normalidad', 'Todos los movimientos de este Pokémon son de tipo normal.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Piel seca', 'Pierde PS si hace calor. Los recupera con agua.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Pies rápidos', 'Potencia la velocidad si hay problemas de estado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Poder solar', 'Aumenta el ataque esp. y baja PS con sol.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Puño férreo', 'Aumenta el poder de los puños.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Recogemiel', 'El Pokémon recoge miel de donde puede.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Resquicio', 'Daña al rival que le ha dado el golpe de gracia.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Rezagado', 'El Pokémon se moverá en segundo lugar.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Rivalidad', 'Sube el ataque si el rival es del mismo sexo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Roca sólida', 'Reduce el poder de los ataques super efectivos del rival.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Rompemoldes', 'No importan las habilidades para usar movimientos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Simple', 'Cambia las características de la forma más audaz.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Tumbos', 'Sube la evasión si el Pokémon está confuso.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Zoquete', 'El Pokémon no puede usar ningún objeto equipado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Allanamiento', 'Los ataques del usuario no se ven afectados por ataques como Protección o Detección.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Alma cura', 'Esta habilidad permite eliminar todos los problemas de estado de un compañero Pokémon en plena batalla.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Armadura frágil', 'Cuando el Pokémon es golpeado con ataques físicos, su Defensa se reduce un nivel pero su Velocidad aumenta un nivel.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Autoestima', 'Consiste en subir el ataque cuando debilitas a un rival.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Bromista', 'Hace que los ataques de efectos tengan prioridad.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cálculo final', 'Hace que los movimientos sean mas poderosos si son utilizados al último.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cobardía', 'Incrementa la Velocidad del Pokémon al enfrentarse a determinados tipos de Pokémon contra los que presenta debilidad.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Compensación', 'Cuando el Pokémon tiene su PS al máximo, esta habilidad reduce el daño recibido del ataque rival.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Competitivo', 'Los efectos de esta habilidad hacen que si al usuario le reducen una característica, sube dos puntos de ataque.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Compiescolta', 'Esta habilidad le brinda un poco de protección ante ataques de aliados haciendo que el poseedor de esta habilidad reciba menos daño del normal.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cosecha', 'El Pokémon puede utilizar la misma Baya de manera indefinida en batalla.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cuerpo maldito', 'Todo aquel rival que golpee a un Pokémon con esta habilidad tiene un 30% de probabilidad de ver anulado temporalmente el uso del movimiento utilizado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Espejo mágico', 'Refleja el efecto de determinados movimientos modificadores.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Flaqueza', 'Si los PS restantes del Pokémon son inferiores al 50% de sus PS máximos, sus estadísticas se reducen.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Funda', 'Esta habilidad hace que el usuario sea invulnerable a los cambios del clima.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Herbívoro', 'Esta habilidad anula los posibles daños que el Pokémon que la tenga pueda sufrir al recibir ataques de tipo planta y aumenta su ataque cuando son golpeados por movimientos de dicho tipo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Hurto', 'Hace que el usuario robe el objeto del rival al mínimo contacto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ilusión', 'Permite transformarse en otros Pokémon.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ímpetu ardiente', 'Incrementa el poder de sus ataques especiales cuando el Pokémon está quemado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ímpetu arena', 'Esta habilidad aumenta la velocidad del Pokémon que la tiene cuando hay una tormenta de arena en plena batalla.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ímpetu tóxico', 'Incrementa el poder los ataques físicos cuando el usuario está envenenado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Impostor', 'El Pokémon se transforma automáticamente en el Pokémon rival al salir a la batalla. En batallas múltiples se transforma en uno de sus rivales al azar.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Justiciero', 'Es una habilidad que da inmunidad ante los ataques de tipo siniestro y sube el ataque al recibir uno.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Metal liviano', 'Hace que el Pokémon pese la mitad');
INSERT INTO habilidades(nombre, efecto) VALUES ('Metal pesado', 'Hace que el Pokémon pese el doble.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Modo Daruma', 'Permite al pokemon usuario cambiar de forma cuando tenga menos del 50 % de PS, revirtiendo el Ataque por el Ataque especial.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Momia', 'Su efecto consiste en transformar la habilidad del oponente en Momia cuando el usuario es atacado por un ataque físico o de contacto, lo que da como resultado que el Pokémon pierda su habilidad y le sea inútil la de momia pues no tiene alguna otra característica especial.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Nerviosismo', 'Esta habilidad anula el uso de las bayas.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Piel milagro', 'Esta habilidad evita que el pokémon sea afectado por ataques que no hagan daño.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Poder arena', 'Esta habilidad aumenta el poder de los ataques de tipo tierra, roca y acero cuando hay una tormenta de arena en plena batalla.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Potencia bruta', 'Los efectos secundarios de los ataques no se cumplen, pero se hacen más fuertes.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Punta acero', 'Provoca daño al rival que haga contacto con este Pokémon.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Regeneración', 'Recupera un tercio de sus PS (HP) cuando lo regresas a su Pokeball en batalla.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Respondón', 'Los movimientos que suben estadísticas las bajan, y viceversa.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Sacapecho', 'Evita que le bajen la defensa al Pokémon usuario.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Telepatía', 'Con esta habilidad, ataques como terremoto o explosión no afectaran al Pokémon.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Terravoltaje', 'Hace que las otras habilidades no tengan efecto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Tinovictoria', 'Aumenta la precisión del Pokemon.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Toque tóxico', 'Los movimientos de contacto del poseedor tienen una probabilidad del 30% de envenenar al oponente');
INSERT INTO habilidades(nombre, efecto) VALUES ('Turbollama', 'Hace que las otras habilidades no tengan efecto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Veleta', 'Provoca que una de las estadísticas del Pokémon se incremente en dos niveles mientras otra se reduce en uno.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Alas vendaval', 'Otorga prioridad +1 a los movimientos de tipo volador.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Antibalas', 'Hace al usuario inmune a los siguientes movimientos: Bola Hielo, Bola voltio, Bomba ácida, Bomba fango, Bomba Germen, Bomba Huevo, Bomba Imán, Bomba Lodo, Bola Sombra, Desenrollar, Energibola, Esfera Aural, Giro Bola, Meteorobola, Onda Certera, Presa, Pulpocañón, Recurrente y Bomba ígnea');
INSERT INTO habilidades(nombre, efecto) VALUES ('Amor filial', 'Permite atacar dos veces en un mismo turno, un ataque de su cría y otro del propio Pokémon.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Aura feérica', 'Potencia los movimientos de tipo Hada de todos los Pokémon en el combate.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Aura oscura', 'Potencia los movimientos de tipo Siniestro de todos los Pokémon en el combate.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Baba', 'Baja en un nivel la velocidad del Pokémon que use un movimiento de contacto contra el poseedor de la habilidad.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Cambio táctico', 'Cambia la forma y las estadísticas del Pokémon dependiendo de sus movimientos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Carrillo', 'Cuando un Pokémon con esta habilidad se come una baya en combate, además de obtener el efecto habitual de esa baya, recuperará PS.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Garra dura', 'Aumenta el poder de los ataques físicos de contacto.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Mar del albor', 'Cambia el clima a diluvio.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Megadisparador', 'Aumenta la potencia de movimientos de pulsos, como hidropulso y pulso umbrío, haciéndolos aún más devastadores.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Mandíbula fuerte', 'Aumenta la potencia de movimientos en los que se requiere morder, como triturar o mordisco.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Manto frondoso', 'Aumenta la defensa especial del usuario si se usa el movimiento campo de hierba.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Mutatipo', 'Cambia el tipo del Pokémon al del movimiento que va a usar.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Pelaje recio', 'Reduce a la mitad el daño recibido por ataques físicos.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Piel celeste', 'Cambia el tipo de los movimientos de tipo normal por tipo volador.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Piel feérica', 'Cambia el tipo de los movimientos de tipo normal por tipo hada.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Piel helada', 'Convierte los movimientos de tipo normal en tipo hielo.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Prestidigitador', 'Permite al usuario robar el objeto del oponente.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Ráfaga delta', 'Cambia el clima a turbulencias en batalla');
INSERT INTO habilidades(nombre, efecto) VALUES ('Rompeaura', 'Invierte todas las habilidades de aura.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Simbiosis', 'Hace que el usuario sea capaz de pasar un objeto a un aliado.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Tenacidad', 'Si al usuario le reducen una característica, sube dos puntos de ataque especial.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Tierra del ocaso', 'Cambia el clima a sol abrasador en batalla');
INSERT INTO habilidades(nombre, efecto) VALUES ('Velo aroma', 'Protege a los aliados de movimientos que afecten a su mente, como atracción.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Velo dulce', 'Evita que los Pokémon aliados se duerman durante el combate.');
INSERT INTO habilidades(nombre, efecto) VALUES ('Velo flor', 'Evita que bajen las características de los Pokémon de tipo planta aliados.');
